version: '3.7'
services:
  mysql-db:
    container_name: 'mysql-db'
    image: 'mysql'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=mysql
      - MYSQL_DATABASE=collective

#    volumes:
#      - "./mysql"

#    networks:
#      - internal-net

  collective-app:
    container_name: 'collective-app'
    image: 'collective-assessment'
    ports:
      - '4000:8080'
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/collective?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false

#    volumes:
#      - "./app"

#    networks:
#      - internal-net
#
#  networks:
#    internal-net:
#      driver: bridge